image: haskell:8.6.3

.variables: &stack_vars
  STACK_ROOT: ${CI_PROJECT_DIR}/.stack-root
  STACK_WORK: ${PACKAGE}/.stack-work
  STACK: >-
    stack
    --resolver=${RESOLVER}
    --no-terminal
    --stack-root ${CI_PROJECT_DIR}/.stack-root
    --work-dir .stack-work
  COVERAGE_DIR: ${CI_PROJECT_DIR}/coverage/${PACKAGE}

.stack_build: &stack_build
  before_script:
    - mkdir -p ${STACK_ROOT}
    - cd ${PACKAGE}
    - ${STACK} --install-ghc test --only-dependencies
  script:
    - ${STACK} test --coverage
  after_script:
    - mkdir -p ${COVERAGE_DIR} ${BIN_DIR}
    - cd ${PACKAGE}
    - mv `${STACK} path --local-hpc-root`/* ${COVERAGE_DIR}
  cache:
    paths:
      - ${STACK_ROOT}
      - ${STACK_WORK}
  artifacts:
    paths:
      - ${COVERAGE_DIR}


.cabal_build: &cabal_build
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends software-properties-common
    - apt-add-repository ppa:hvr/ghc
    - apt-get update && apt-get install -y --no-install-recommends ghc-${GHC_VERSION}
    - PATH="/opt/cabal/bin:$PATH"
    - PATH="/opt/ghc/${GHC_VERSION}/bin:$PATH"
    - cabal update
    - cd ${PACKAGE}
    - cabal check
    - (cd ../${TEST_DEP}; cabal install)
    - cabal install --enable-tests --only-dependencies
  script:
    - cabal test --show-details=always
    - cabal sdist
  after_script:
    - rm -fv ${HOME}/.cabal/packages/hackage.haskell.org/build-reports.log
    # remove files that are regenerated by 'cabal update'
    - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
    - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
    - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
    - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
    - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
    - rm -rfv $HOME/.cabal/packages/head.hackage
  cache:
    paths:
      - ${HOME}/.cabal/packages
      - ${HOME}/.cabal/store


attoparsec-varword_lts-9.19:
  <<: *stack_build
  variables:
    PACKAGE: attoparsec-varword
    RESOLVER: lts-9.19
    <<: *stack_vars

bytestring-builder-varword_lts-9.19:
  <<: *stack_build
  variables:
    PACKAGE: bytestring-builder-varword
    RESOLVER: lts-9.19
    <<: *stack_vars


attoparsec-varword_lts-11.7:
  <<: *stack_build
  variables:
    PACKAGE: attoparsec-varword
    RESOLVER: lts-11.7
    <<: *stack_vars

bytestring-builder-varword_lts-11.7:
  <<: *stack_build
  variables:
    PACKAGE: bytestring-builder-varword
    RESOLVER: lts-11.7
    <<: *stack_vars


attoparsec-varword_ghc-8.0.2:
  <<: *cabal_build
  variables:
    PACKAGE: attoparsec-varword
    GHC_VERSION: 8.0.2
    TEST_DEP: bytestring-builder-varword

bytestring-builder-varword_ghc-8.0.2:
  <<: *cabal_build
  variables:
    PACKAGE: bytestring-builder-varword
    GHC_VERSION: 8.0.2
    TEST_DEP: attoparsec-varword


attoparsec-varword_ghc-8.2.2:
  <<: *cabal_build
  variables:
    PACKAGE: attoparsec-varword
    GHC_VERSION: 8.2.2
    TEST_DEP: bytestring-builder-varword

bytestring-builder-varword_ghc-8.2.2:
  <<: *cabal_build
  variables:
    PACKAGE: bytestring-builder-varword
    GHC_VERSION: 8.2.2
    TEST_DEP: attoparsec-varword


attoparsec-varword_ghc-8.4.2:
  <<: *cabal_build
  variables:
    PACKAGE: attoparsec-varword
    GHC_VERSION: 8.4.2
    TEST_DEP: bytestring-builder-varword

bytestring-builder-varword_ghc-8.4.2:
  <<: *cabal_build
  variables:
    PACKAGE: bytestring-builder-varword
    GHC_VERSION: 8.4.2
    TEST_DEP: attoparsec-varword


pages:
  stage: deploy
  dependencies:
    - attoparsec-varword_lts-11.7
  script:
    mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 10 days
  only:
    - master
