# Derived from https://raw.githubusercontent.com/commercialhaskell/stack/master/doc/travis-simple.yml
sudo: false
notifications:
  email: false
  irc:
    channels:
     - "chat.freenode.net#concertdaw"
    on_success: change
    on_failure: change
    template:
     - "%{repository_name}/%{branch} %{result}: %{build_url}"

_stack_build: &_stack_build
  language: generic
  cache:
    directories:
      - $HOME/.stack
      - $HOME/.local/bin
      - $TRAVIS_BUILD_DIR/.stack-work
  addons:
    apt:
      packages: []
  before_install:
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - stack upgrade --binary-only || travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - git clone https://github.com/concert/stack-hpc-coveralls.git
    - $(cd stack-hpc-coveralls; stack install stack-hpc-coveralls)
    - cd $PACKAGE
  install:
    - pwd
    - stack --resolver=$RESOLVER --no-terminal --install-ghc test --only-dependencies
  script:
    - pwd
    - stack --resolver=$RESOLVER --no-terminal test --coverage
  after_script:
    - pwd
    - shc ${PACKAGE} ${PACKAGE}-test

_cabal_build: &_cabal_build
  language: generic
  cache:
    directories:
      - $HOME/.cabal/packages
      - $HOME/.cabal/store
  before_cache:
    - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
    # remove files that are regenerated by 'cabal update'
    - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
    - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
    - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
    - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
    - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
    - rm -rfv $HOME/.cabal/packages/head.hackage
  addons:
    apt:
      packages: &_cabal_apt_packages
        - cabal-install-2.0
  before_install:
    - PATH="/opt/cabal/2.0/bin:$PATH"
    - PATH="/opt/ghc/${GHC_VERSION}/bin:$PATH"
    - cabal update
    - cd $PACKAGE
  install:
    - cabal check
    - (cd ../${TEST_DEP}; cabal install)
    - cabal install --enable-tests --only-dependencies
  script:
    - cabal test --show-details=always
    - cabal sdist


matrix:
  include:
  # FIXME: there doesn't seem to be a good way to keep this DRY:
   - <<: *_stack_build
     env: RESOLVER=lts-9.19 PACKAGE=attoparsec-varword
   - <<: *_stack_build
     env: RESOLVER=lts-9.19 PACKAGE=bytestring-builder-varword

   - <<: *_stack_build
     env: RESOLVER=lts-11.7 PACKAGE=attoparsec-varword
   - <<: *_stack_build
     env: RESOLVER=lts-11.7 PACKAGE=bytestring-builder-varword

   - <<: *_cabal_build
     env: PACKAGE=attoparsec-varword GHC_VERSION=8.2.2 TEST_DEP=bytestring-builder-varword
     addons:
       apt:
         packages: [*_cabal_apt_packages, ghc-8.2.2]
         sources: [hvr-ghc]

   - <<: *_cabal_build
     env: PACKAGE=bytestring-builder-varword GHC_VERSION=8.2.2 TEST_DEP=attoparsec-varword
     addons:
       apt:
         packages: [*_cabal_apt_packages, ghc-8.2.2]
         sources: [hvr-ghc]
